Garaio.Academy.Web/Models/TaskViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Garaio.Academy.Web.Models
{
    public class TaskViewModel
    {
        public int Id { get; set;}
        
        [Display(Name = "Name des Tasks")]
        [Required(ErrorMessage = "Der Name ist ein Pflichtfeld")]
        public string Name { get; set; }
        
        [Display(Name = "Notizen des Tasks")]
        [Required(ErrorMessage = "Die Notizen sind ein Pflichtfeld")]
        public string Notes { get; set;}
        
        [Display(Name = "Task abgeschlossen")]
        public bool Done { get; set;}
    }
}

Garaio.Academy.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Garaio.Academy.Core;
using Garaio.Academy.Data;
using Garaio.Academy.Web.Models;
using Garaio.Academy.Core.Enums;
using Garaio.Academy.Core.Options;
using Microsoft.Extensions.Options;

namespace Garaio.Academy.Web.Controllers
{
    public class HomeController : Controller
    {
        private ITaskRepository _taskRepository;

        private IOptions<TaskGridSettings> _settings;

        public HomeController(ITaskRepository taskRepository, IOptions<TaskGridSettings> settings)
        {
            if (taskRepository == null)
            {
                throw new ArgumentException(nameof(taskRepository));
            }

            this._taskRepository = taskRepository;
            this._settings = settings;
        }

        [HttpGet]
        public IActionResult Index(StatusMessageIds? message = null)
        {
            ViewData["AlertType"] = message.ToString().Contains("Success") ? "success" : "danger";
            ViewData["StatusMessage"] =
				message == StatusMessageIds.CreateSuccess ? "Task erfolgreich gespeichert"
				: message == StatusMessageIds.Error ? "Task konnte nicht gespeichert werden"
				: string.Empty;

            IQueryable<TaskItem> tasks = this._taskRepository.GetAll().Take(this._settings.Value.ItemCount);
            IQueryable<TaskViewModel> model = tasks.Select(t =>
                new TaskViewModel { Id = t.Id, Name = t.Name, Notes = t.Notes, Done = t.Done });
            
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            TaskViewModel model = new TaskViewModel();

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int taskId)
        {
            TaskItem task = this._taskRepository.GetById(taskId);
            TaskViewModel model = new TaskViewModel
            {
                Id = task.Id,
                Name = task.Name,
                Notes = task.Notes,
                Done = task.Done
            };

            return View(model);
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Garaio.Academy.Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Garaio.Academy.Core;
using Garaio.Academy.Data;
using Garaio.Academy.Web.Models;
using Garaio.Academy.Core.Enums;

namespace Garaio.Academy.Web.Controllers
{
    public class TaskController : Controller
    {
        private ITaskRepository _taskRepository;

        public TaskController(ITaskRepository taskRepository)
        {
            if (taskRepository == null)
            {
                throw new ArgumentException(nameof(taskRepository));
            }

            this._taskRepository = taskRepository;
        }

        [HttpPost]
        public IActionResult CreateTask(TaskViewModel model)
        {
            if (model == null)
            {
                throw new ArgumentException(nameof(model));
            }

            try
            {
                if (ModelState.IsValid)
                {
                    TaskItem task = new TaskItem
                    {
                        Name = model.Name,
                        Notes = model.Notes
                    };

                    this._taskRepository.Add(task);
                    this._taskRepository.SaveChanges();
                }   
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(HomeController.Index), "Home", new { Message = StatusMessageIds.Error });
            }

            return RedirectToAction(nameof(HomeController.Index), "Home", new { Message = StatusMessageIds.CreateSuccess });
        }

        [HttpPost]
        public IActionResult EditTask(TaskViewModel model)
        {
            if (model == null)
            {
                throw new ArgumentException(nameof(model));
            }

            try
            {
                if (ModelState.IsValid)
                {
                    TaskItem task = this._taskRepository.GetById(model.Id);
                    task.Name = model.Name;
                    task.Notes = model.Notes;
                    task.Done = model.Done;

                    this._taskRepository.Update(task);
                    this._taskRepository.SaveChanges();
                }   
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(HomeController.Index), "Home", new { Message = StatusMessageIds.Error });
            }

            return RedirectToAction(nameof(HomeController.Index), "Home", new { Message = StatusMessageIds.CreateSuccess });
        }
    }
}

Garaio.Academy.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Garaio.Academy.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Garaio.Academy.Web/Views/Home/Create.cshtml
@{
    ViewData["Title"] = "Neuer Task";
}

@model Garaio.Academy.Web.Models.TaskViewModel

<h2>@ViewData["Title"]</h2>

<form asp-controller="Task" asp-action="CreateTask" method="POST" class="form-horizontal">
    <fieldset>
        <legend>Task Daten</legend>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-8 input-group">
                <input Id="Name" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-8 input-group">
                <input Id="Notes" asp-for="Notes" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>    
    </fieldset>
    <div>
        <button type="submit" class="btn btn-default">Speichern</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-default">Abbrechen</a>
    </div>
</form>

Garaio.Academy.Web/Views/Home/Edit.cshtml
@{
    ViewData["Title"] = "Neuer Task";
}

@model Garaio.Academy.Web.Models.TaskViewModel

<h2>@ViewData["Title"]</h2>

<form asp-controller="Task" asp-action="EditTask" method="POST" class="form-horizontal">
    <fieldset>
        <legend>Task Daten</legend>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-8 input-group">
                <input Id="Name" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-8 input-group">
                <input Id="Notes" asp-for="Notes" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Done" class="col-md-2 control-label"></label>
            <div class="col-md-8 input-group">
                <select asp-for="Done" class="form-control">
                    <option value="false">Nicht abgeschlossen</option>
                    <option value="true">Abgeschlossen</option>
                </select>
            </div>            
        </div>
        <input type="hidden" name="Id" asp-for="Id" />    
    </fieldset>
    <div>
        <button type="submit" class="btn btn-default">Speichern</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-default">Abbrechen</a>
    </div>
</form>

Garaio.Academy.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Task Übersicht";
}

@model IEnumerable<Garaio.Academy.Web.Models.TaskViewModel>

<h2>@ViewData["Title"]</h2>

@if (!string.IsNullOrEmpty(ViewData["StatusMessage"]?.ToString()))
{
    <div class="alert alert-@(ViewData["AlertType"]) fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewData["StatusMessage"]
    </div>
}

<p>
    <a asp-action="Create">Neuer Task erstellen</a>
</p>

<table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Beschreibung</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var task in Model)
            {
                <tr>
                    <td>@task.Name</td><td>@task.Notes</td>
                    <td>
                        @(task.Done ? Html.Raw("Abgeschlossen") : Html.Raw("Nicht Abgeschlosen"))
                    </td>
                    <td><a asp-action="Edit" asp-route-taskid="@task.Id">Bearbeiten</a></td>
                </tr>
            }
        </tbody>
</table>

Garaio.Academy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iTask</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">iTask</a>
            </div>
            <!--<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>-->
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - iTask</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>